[package]
name = "radicalise"
version = "0.1.4"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
axum = "0.8.4"
lazy_static = "1.5.0"
serde = "1.0.219"
sqlx = { version = "0.8.6", features = ["runtime-tokio-native-tls", "sqlite"] }
tokio = { version = "1.45.1", features = ["rt-multi-thread"] }
tower = "0.5.2"
tower-http = { version = "0.6.6", features = ["cors", "fs"] }
utoipa = "5.3.1"
utoipa-axum = "0.2.0"
utoipa-swagger-ui = { version = "9.0.2", features = ["axum"] }
