# Copy this file to "inventory.yaml" to use it.
# Populate it with your own hosts and variables.
all:
  vars:
    ansible_become: true
  hosts:
    #localhost:
    #  ansible_connection: ansible.builtin.local
    #  gather_facts: false
    #  ansible_become: false
    brassica.radhousing.org:
      ansible_ssh_user: root
      ansible_become: false
      traefik_acme_email: jade@hopepunk.me
      resend_api_key: YOUR_KEY_HERE
      base_url: YOUR SITE URL HERE
