all:
  vars:
    ansible_become: true
  hosts:
    #localhost:
    #  ansible_connection: ansible.builtin.local
    #  gather_facts: false
    #  ansible_become: false
    brassica.radhousing.org:
      ansible_ssh_user: root
      ansible_become: false
      traefik_acme_email: jade@hopepunk.me
